version: "3.9"

services:
  flask_service:
    image: api
    volumes:
      - ./IngestionApp:/app
      - ./data:/data
    ports:
      - "56733:80"
      
  rq-worker:
    image: rq_worker
    command: rq worker -u redis://rq-server:6379 queue
    deploy:
      replicas: 3
    volumes:
      - ./data:/usr/src/app/data

  rq-server:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/usr/src/app/data
      
  client:
    image: ingestion
    tty: true 
    deploy:
      replicas: 1
      
  ## Config Servers
  config01:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --oplogSize 16
    volumes:
      - ./scripts:/scripts
  config02:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --oplogSize 16
    volumes:
      - ./scripts:/scripts
  config03:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Shards
  shard01a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01
    volumes:
      - ./scripts:/scripts
  shard01b:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01
    volumes:
      - ./scripts:/scripts
  shard02a:
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02 
    volumes:
      - ./scripts:/scripts
  shard02b:
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02
    volumes:
      - ./scripts:/scripts
  shard03a:
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet shard03
    volumes:
      - ./scripts:/scripts
  shard03b:
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet shard03
    volumes:
      - ./scripts:/scripts

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017,config03:27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard02a
      - shard02b
      - shard03a
      - shard03b
      

